# Generated by Django 5.0.6 on 2024-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(unique=True)),
                ('num_dice', models.IntegerField()),
                ('num_games', models.IntegerField()),
                ('wait_time', models.IntegerField()),
            ],
        ),
    ]
